### PR TITLE
Feat/loader

### PR DESCRIPTION
**Pull request by rinzler99**
https://www.loom.com/share/9fd568866fb24ac589c2373aac5101f6

### CODE REVIEW

**Comment by himanshuchawla009** [comment]
Screenshot_20221206_193358

scrollbar showing up on clicking view more @lionellbriones

**Comment by himanshuchawla009** [comment]
not able to use appLogo any more, I used following code snippet:-

```
 new Web3Auth({
          chainConfig: ethChainConfig,
          clientId: config.clientId[this.openloginNetwork],
          authMode: "DAPP",
          enableLogging: true,
          uiConfig: {
            theme: "light",
            appLogo: "https://avatars.githubusercontent.com/u/72950769?s=200&v=4",
          },
        });
        ```

**Comment by chaitanyapotti** [comment]
Scroll only happens on view more if the screen height is less than 620px.. this is expected behaviour

**Comment by chaitanyapotti** [comment]
appLogo will be shown along with whitelabel in next release

**Comment by himanshuchawla009** [comment]
> Scroll only happens on view more if the screen height is less than 620px.. this is expected behaviour

ok

**Review by chaitanyapotti — APPROVED** [review]
lgtm

**Review by himanshuchawla009 — APPROVED** [review]
lgtm

**Pull request merged**
